name: intention
favicon: null
layout_spectrum: 0.4928
typography_spectrum: 0.50899
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a1c2d'
    - '#63477a'
    - '#997984'
    - '#bfb8ca'
    - '#fadeaf'
  brandStrength: 0.5
  lightness: 0.6835455358959734
  saturation: 0.5625
  rhythmicContrast: 0.024723384995013475
purpose: []
